# Generated by Django 2.2.10 on 2020-04-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_set_location',
            field=models.BooleanField(default=False),
        ),
    ]
